version: "3"
services:
    mysql:
        image: "aladdinding/mysql:5.7"
        ports: 
        - "3307:3306"
        volumes: 
        - /data/atlassian-mysql:/var/atlassian/mysql
        environment: 
        - MYSQL_ROOT_PASSWORD=atlassian
        restart: always
    confluence:
        image: "aladdinding/confluence:latest"
        ports: 
        - "8601:8090"
        volumes: 
        - /data/confluence:/var/atlassian/confluence
        environment: 
        - TZ="Asia/Shanghai"
        links:
        - mysql
        restart: always
    jira:
        image: "aladdinding/jira:latest"
        ports: 
        - "8600:8080"
        volumes: 
        - /data/jira:/var/atlassian/jira
        environment: 
        - TZ="Asia/Shanghai"
        links:
        - mysql
        restart: always

